const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,data:null,activeTab:'dashboard',invoicePage:1,pageSize:50,users:[],adminLookup:null};
const BUCKETS=["Blm Jth Tempo","C1 (1-14)","C2 (15-30)","C3 (31-60)","C4 (61-90)","C5 (91-120)","C6 (>120)"];
const REQUIRED_HEADERS=["Tanggal Faktur","Month","year","overdue hari","klasifikasi","No SJ","No. Faktur","ID Customer","Customer","Salesman","SPV","Gudang","Total pembelian","Cash","Sudah Bayar","Sisa Piutang","Histori Sales","Histori Kesimpulan","Histori Terupdate"];
const monthNames=["Jan","Feb","Mar","Apr","Mei","Jun","Jul","Agu","Sep","Okt","Nov","Des"];

function toast(msg,type='success'){const t=$('#toast');t.textContent=msg;t.className=`toast show ${type}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.className='toast',3500)}
function fmtMoney(v){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0))}
function fmtCompact(v){const n=Number(v||0);if(Math.abs(n)>=1e9)return`Rp ${(n/1e9).toLocaleString('id-ID',{maximumFractionDigits:2})} M`;if(Math.abs(n)>=1e6)return`Rp ${(n/1e6).toLocaleString('id-ID',{maximumFractionDigits:1})} Jt`;return fmtMoney(n)}
function fmtPct(v){return v==null?'N/A':`${(Number(v)*100).toLocaleString('id-ID',{minimumFractionDigits:2,maximumFractionDigits:2})}%`}
function fmtScore(v){return Number(v||0).toLocaleString('id-ID',{minimumFractionDigits:2,maximumFractionDigits:2})}
function statusClass(s){return['EXCELLENT','TERCAPAI'].includes(s)?'good':s==='PERLU PERBAIKAN'?'warn':'bad'}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function dateText(iso){if(!iso)return'-';try{return new Date(iso).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'})}catch{return iso}}

async function api(path,options={}){const[routePart,queryPart='']=String(path||'/').split('?');const url=new URL('/.netlify/functions/api',window.location.origin);url.searchParams.set('route',routePart||'/');for(const[k,v]of new URLSearchParams(queryPart).entries())url.searchParams.append(k,v);const r=await fetch(url.toString(),{credentials:'same-origin',headers:{'content-type':'application/json',...(options.headers||{})},...options});let d={};try{d=await r.json()}catch{}if(r.status===401){showLogin();throw new Error(d.error||'Sesi berakhir.')}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function showLogin(){state.user=null;$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')}
function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userName').textContent=state.user.displayName||state.user.username;$('#userRole').textContent=state.user.role;$$('.admin-only').forEach(el=>el.classList.toggle('hidden',state.user.role!=='admin'));$$('.admin-company-only').forEach(el=>el.classList.toggle('hidden',!['admin','company'].includes(state.user.role)))}
async function boot(){try{const m=await api('/me');state.user=m.user;showApp();await loadData()}catch{showLogin()}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';try{const d=await api('/login',{method:'POST',body:JSON.stringify({username:$('#loginUsername').value,password:$('#loginPassword').value})});state.user=d.user;showApp();await loadData()}catch(err){$('#loginError').textContent=err.message}})
$('#logoutBtn').addEventListener('click',async()=>{try{await api('/logout',{method:'POST',body:'{}'})}catch{}showLogin()})
$$('.tab').forEach(btn=>btn.addEventListener('click',()=>switchTab(btn.dataset.tab)));
function switchTab(tab){state.activeTab=tab;$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));$$('.tab-panel').forEach(x=>x.classList.add('hidden'));$(`#tab-${tab}`).classList.remove('hidden');if(tab==='users'&&state.user?.role==='admin')loadUsers()}

async function loadData(){const spv=$('#spvFilter').value||'',sales=$('#salesFilter').value||'',gudang=$('#gudangFilter').value||'';const q=new URLSearchParams();if(spv)q.set('spv',spv);if(sales)q.set('salesman',sales);if(gudang)q.set('gudang',gudang);const d=await api(`/data?${q}`);state.data=d;renderFilters();renderDashboard();renderSales();state.invoicePage=1;renderAgingFilterOptions();renderInvoices();renderUserFormOptions()}
function optionsHtml(list,empty,current=''){return`<option value="">${empty}</option>`+list.map(x=>`<option value="${esc(x)}" ${x===current?'selected':''}>${esc(x)}</option>`).join('')}
function renderFilters(){const d=state.data,sc=d.meta.scope;const spvEl=$('#spvFilter'),salesEl=$('#salesFilter'),gudEl=$('#gudangFilter');spvEl.innerHTML=optionsHtml(d.options.spvs,'Semua SPV / Perusahaan',sc.spv||'');salesEl.innerHTML=optionsHtml(d.options.salesmen,'Semua Salesman',sc.salesman||'');gudEl.innerHTML=optionsHtml(d.options.gudangs,'Semua Gudang',sc.gudang||'');spvEl.value=sc.spv||'';salesEl.value=sc.salesman||'';gudEl.value=sc.gudang||'';spvEl.disabled=['spv','sales'].includes(state.user.role);salesEl.disabled=state.user.role==='sales'||((['admin','company'].includes(state.user.role))&&!sc.spv);$('#periodText').textContent=d.meta.period?.label||'-';$('#updatedText').textContent=`${dateText(d.meta.uploadedAt)} • ${d.meta.sourceFile||'-'}`}
$('#spvFilter').addEventListener('change',()=>{$('#salesFilter').value='';loadData().catch(e=>toast(e.message,'error'))});$('#salesFilter').addEventListener('change',()=>loadData().catch(e=>toast(e.message,'error')));$('#gudangFilter').addEventListener('change',()=>loadData().catch(e=>toast(e.message,'error')));

function renderDashboard(){const d=state.data,k=d.summary.kpi,raw=d.summary.raw,sc=d.meta.scope;const scopeParts=[];if(sc.gudang)scopeParts.push(`Gudang ${sc.gudang}`);if(sc.spv)scopeParts.push(`SPV ${sc.spv}`);if(sc.salesman)scopeParts.push(sc.salesman);$('#scopeTitle').textContent=scopeParts.length?scopeParts.join(' • '):'Total Perusahaan';$('#scoreBadge').innerHTML=`<span>Adjusted Score</span><strong>${fmtScore(k.totalScore)}</strong><em>${esc(k.status)}</em>`;$('#scoreBadge').className=`score-badge ${statusClass(k.status)}`;
  $('#kpiCards').innerHTML=k.details.map(x=>`<article class="kpi-card"><div class="label">${esc(x.label)}</div><div class="actual">${fmtPct(x.actual)}</div><div class="sub"><span>Target ${x.direction==='higher'?'≥':'≤'} ${fmtPct(x.target)}</span><span>Bobot ${(x.weight*100).toFixed(0)}%</span></div><div style="margin-top:10px"><span class="status ${statusClass(x.status)}">${x.status}</span><span style="float:right;font-size:11px;color:#64748b">Score ${fmtScore(x.weightedScore)}</span></div></article>`).join('');
  const total=Number(raw.piutang||0);$('#totalPiutangText').textContent=fmtCompact(total);$('#agingBars').innerHTML=BUCKETS.map((b,i)=>{const v=Number(raw[b]||0),pct=total?Math.min(v/total*100,100):0;return`<div class="aging-row"><span>${esc(b)}</span><div class="bar-track"><div class="bar-fill" style="width:${pct}%;background:${i===6?'#b91c1c':i>=3?'#f59e0b':'#4472c4'}"></div></div><strong class="money">${fmtCompact(v)}</strong></div>`}).join('');
  $('#mainNumbers').innerHTML=[['Penjualan Periode',raw.salesPeriod],['Grand Total Piutang',raw.piutang],['Exposure',`${k.exposure.level} • ${(k.exposure.weight*100).toFixed(0)}%`],['Piutang Belum Lunas',k.belumLunas],['Raw Overdue >30',fmtPct(k.over30Raw)],['Adjusted Overdue >30',fmtPct(k.over30Adjusted)],['Raw Overdue >120',fmtPct(k.over120Raw)],['Adjusted Overdue >120',fmtPct(k.over120Adjusted)]].map(x=>`<div class="number-item"><span>${x[0]}</span><strong>${typeof x[1]==='number'?fmtCompact(x[1]):esc(x[1])}</strong></div>`).join('');
  $('#parameterTable').innerHTML=d.kpiParameters.map(p=>`<tr><td>${esc(p.label)}</td><td>${p.direction==='higher'?'≥':'≤'} ${fmtPct(p.target)}</td><td>${(p.weight*100).toFixed(0)}%</td><td>${p.direction==='higher'?'Higher':'Lower'}</td><td>${esc(p.formula)}</td></tr>`).join('');$('#exposureNote').innerHTML=`<strong>Exposure Adjustment:</strong> ${d.exposureParameters.map(x=>`${x.level} ${x.limit} = ${(x.weight*100).toFixed(0)}% rasio PIC`).join(' • ')}. Rasio yang diblend adalah Overdue &gt;30 dan &gt;120 dengan referensi rasio perusahaan.`;renderRankings()}
function renderRankings(){const sales=state.data.rankings.sales||[],spv=state.data.rankings.spv||[];$('#salesRankingTable').innerHTML=sales.map(x=>`<tr><td class="rank-num">#${x.rank}</td><td><strong>${esc(x.salesman)}</strong></td><td>${esc(x.spv)}</td><td>${esc(x.gudang||'-')}</td><td class="score">${fmtScore(x.kpi.totalScore)}</td><td><span class="status ${statusClass(x.kpi.status)}">${x.kpi.status}</span></td></tr>`).join('')||'<tr><td colspan="6">Tidak ada data ranking.</td></tr>';$('#spvRankingTable').innerHTML=spv.map(x=>`<tr><td class="rank-num">#${x.rank}</td><td><strong>${esc(x.spv)}</strong></td><td>${esc(x.gudang||'-')}</td><td class="score">${fmtScore(x.kpi.totalScore)}</td><td><span class="status ${statusClass(x.kpi.status)}">${x.kpi.status}</span></td></tr>`).join('')||'<tr><td colspan="5">Tidak ada data ranking.</td></tr>'}

function renderSales(){const rows=[...state.data.salesPerformance].sort((a,b)=>(b.kpi?.totalScore??-1)-(a.kpi?.totalScore??-1));$('#salesTable').innerHTML=rows.map(x=>{if(!x.kpi)return`<tr><td>${esc(x.spv)}</td><td>${esc(x.gudang||'-')}</td><td><strong>${esc(x.salesman)}</strong></td><td class="money">${fmtCompact(x.salesPeriod)}</td><td class="money">${fmtCompact(x.piutang)}</td><td colspan="8"><span class="status warn">LEGACY PIUTANG</span></td><td>-</td><td>Monitoring</td></tr>`;const k=x.kpi,m=Object.fromEntries(k.details.map(v=>[v.key,v.actual]));return`<tr><td>${esc(x.spv)}</td><td>${esc(x.gudang||'-')}</td><td><strong>${esc(x.salesman)}</strong></td><td class="money">${fmtCompact(x.salesPeriod)}</td><td class="money">${fmtCompact(x.piutang)}</td><td>${esc(k.exposure.level)} ${(k.exposure.weight*100).toFixed(0)}%</td><td>${fmtPct(m.collectionRate)}</td><td>${fmtPct(m.piutangBelumLunasRatio)}</td><td>${fmtPct(k.over30Raw)}</td><td>${fmtPct(k.over30Adjusted)}</td><td>${fmtPct(k.over120Raw)}</td><td>${fmtPct(k.over120Adjusted)}</td><td>${fmtPct(k.c1SalesRatio)}</td><td class="score">${fmtScore(k.totalScore)}</td><td><span class="status ${statusClass(k.status)}">${k.status}</span></td></tr>`}).join('')||'<tr><td colspan="15">Tidak ada data.</td></tr>'}

function renderAgingFilterOptions(){const d=state.data,curSpv=$('#agingSpvFilter').value,curGud=$('#agingGudangFilter').value;const spvs=[...new Set((d.invoices||[]).map(x=>x.spv).filter(Boolean))].sort();const guds=[...new Set((d.invoices||[]).map(x=>x.gudang).filter(Boolean))].sort();$('#agingSpvFilter').innerHTML=optionsHtml(spvs,'Semua SPV');$('#agingGudangFilter').innerHTML=optionsHtml(guds,'Semua Gudang');if(spvs.includes(curSpv))$('#agingSpvFilter').value=curSpv;if(guds.includes(curGud))$('#agingGudangFilter').value=curGud}
function filteredInvoices(){const q=$('#invoiceSearch').value.trim().toLowerCase(),hist=$('#historyExcelSearch').value.trim().toLowerCase(),aging=$('#agingFilter').value,spv=$('#agingSpvFilter').value,gud=$('#agingGudangFilter').value;return(state.data?.invoices||[]).filter(x=>(!aging||x.klasifikasi===aging)&&(!spv||x.spv===spv)&&(!gud||x.gudang===gud)&&(!q||[x.customer,x.noFaktur,x.salesman,x.spv,x.gudang,x.idCustomer].some(v=>String(v||'').toLowerCase().includes(q)))&&(!hist||[x.historiSales,x.historiKesimpulan,x.historiTerupdate].some(v=>String(v||'').toLowerCase().includes(hist))))}
function historyHtml(x){const parts=[];if(x.historiSales)parts.push(`<div class="history-line"><b>Sales:</b> ${esc(x.historiSales)}</div>`);if(x.historiKesimpulan)parts.push(`<div class="history-line"><b>Kesimpulan:</b> ${esc(x.historiKesimpulan)}</div>`);if(x.historiTerupdate)parts.push(`<div class="history-line"><b>Terupdate:</b> ${esc(x.historiTerupdate)}</div>`);return parts.join('')||'-'}
function renderInvoices(){const all=filteredInvoices(),pages=Math.max(1,Math.ceil(all.length/state.pageSize));state.invoicePage=Math.min(state.invoicePage,pages);const from=(state.invoicePage-1)*state.pageSize,rows=all.slice(from,from+state.pageSize);$('#invoiceCount').textContent=`${all.length.toLocaleString('id-ID')} data`;$('#pageText').textContent=`${state.invoicePage} / ${pages}`;$('#prevPage').disabled=state.invoicePage<=1;$('#nextPage').disabled=state.invoicePage>=pages;$('#invoiceTable').innerHTML=rows.map(x=>`<tr><td><span class="status ${x.klasifikasi==='C6 (>120)'?'bad':x.overdueHari>30?'warn':'good'}">${esc(x.klasifikasi)}</span></td><td>${esc(x.noFaktur)}<br><small>${esc(x.tanggalFaktur)}</small></td><td><strong>${esc(x.customer)}</strong><br><small>${esc(x.idCustomer)}</small></td><td>${esc(x.gudang)}</td><td>${esc(x.spv)}</td><td>${esc(x.salesman)}</td><td class="money"><strong>${fmtMoney(x.sisaPiutang)}</strong></td><td>${Number(x.overdueHari||0)} hari</td><td class="history-excel">${historyHtml(x)}</td><td><div class="history-editor"><textarea maxlength="1500" data-history="${esc(x.rowId)}" placeholder="Ketik histori terkini...">${esc(x.manualHistory?.text||'')}</textarea><button class="btn btn-secondary save-history" data-id="${esc(x.rowId)}">Simpan</button></div>${x.manualHistory?`<small>${esc(x.manualHistory.updatedBy)} • ${dateText(x.manualHistory.updatedAt)}</small>`:''}</td></tr>`).join('')||'<tr><td colspan="10">Tidak ada data sesuai filter.</td></tr>';$$('.save-history').forEach(b=>b.addEventListener('click',()=>saveHistory(b.dataset.id,b)))}
['invoiceSearch','historyExcelSearch'].forEach(id=>$(`#${id}`).addEventListener('input',()=>{state.invoicePage=1;renderInvoices()}));['agingFilter','agingSpvFilter','agingGudangFilter'].forEach(id=>$(`#${id}`).addEventListener('change',()=>{state.invoicePage=1;renderInvoices()}));$('#prevPage').addEventListener('click',()=>{state.invoicePage--;renderInvoices()});$('#nextPage').addEventListener('click',()=>{state.invoicePage++;renderInvoices()});
async function saveHistory(rowId,btn){const ta=document.querySelector(`textarea[data-history="${CSS.escape(rowId)}"]`);btn.disabled=true;try{const d=await api('/history',{method:'POST',body:JSON.stringify({rowId,text:ta.value})});const inv=state.data.invoices.find(x=>x.rowId===rowId);if(inv)inv.manualHistory=d.manualHistory;toast('Histori piutang tersimpan.');renderInvoices()}catch(e){toast(e.message,'error')}finally{btn.disabled=false}}

function excelDate(v){if(v==null||v==='')return'';if(typeof v==='number'&&window.XLSX?.SSF){const d=XLSX.SSF.parse_date_code(v);if(d)return`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`}return String(v)}
function n(v){if(typeof v==='string')v=v.replace(/,/g,'').trim();const x=Number(v);return Number.isFinite(x)?x:0}
function blankAgg(){const x={salesPeriod:0,totalPembelian:0,cash:0,sudahBayar:0,piutang:0};BUCKETS.forEach(b=>x[b]=0);return x}
function addAgg(a,r,latestYear,latestMonth){const total=n(r['Total pembelian']),cash=n(r.Cash),paid=n(r['Sudah Bayar']),sisa=n(r['Sisa Piutang']);a.totalPembelian+=total;a.cash+=cash;a.sudahBayar+=paid;if(n(r.year)===latestYear&&n(r.Month)===latestMonth)a.salesPeriod+=total;const k=String(r.klasifikasi||'').trim();if(BUCKETS.includes(k)){a[k]+=sisa;a.piutang+=sisa}}
function getMap(map,key,extra={}){if(!map.has(key))map.set(key,{...extra,...blankAgg()});return map.get(key)}
async function parseExcel(file){if(!window.XLSX)throw new Error('Library Excel belum siap. Refresh halaman lalu coba lagi.');const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',dense:true,cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]],data=XLSX.utils.sheet_to_json(ws,{defval:'',raw:true});if(!data.length)throw new Error('Sheet pertama tidak memiliki data.');const available=new Set(Object.keys(data[0])),missing=REQUIRED_HEADERS.filter(h=>!available.has(h));if(missing.length)throw new Error(`Kolom wajib tidak ditemukan: ${missing.join(', ')}`);
  const invoiceRows=data.filter(r=>String(r['No. Faktur']||'').trim());let latestYear=0,latestMonth=0;for(const r of invoiceRows){const y=n(r.year),m=n(r.Month);if(y&&m&&(y>latestYear||(y===latestYear&&m>latestMonth))){latestYear=y;latestMonth=m}}if(!latestYear||!latestMonth)throw new Error('Periode terbaru tidak dapat dideteksi.');
  const company=blankAgg(),spvMap=new Map(),gudMap=new Map(),salesMap=new Map(),spvGudMap=new Map(),salesGudMap=new Map(),openInvoices=[],salesSpvCounts=new Map(),salesGudSpvCounts=new Map();
  const bump=(holder,key,value)=>{if(!holder.has(key))holder.set(key,new Map());const m=holder.get(key);m.set(value,(m.get(value)||0)+1)};
  const dominant=m=>{let best='',count=-1;for(const[k,v]of(m||new Map()))if(v>count){best=k;count=v}return best};
  for(const r of invoiceRows){const spv=String(r.SPV||'').trim(),sales=String(r.Salesman||'').trim(),gud=String(r.Gudang||'').trim();addAgg(company,r,latestYear,latestMonth);if(spv)addAgg(getMap(spvMap,spv),r,latestYear,latestMonth);if(gud)addAgg(getMap(gudMap,gud),r,latestYear,latestMonth);if(sales){addAgg(getMap(salesMap,sales,{salesman:sales}),r,latestYear,latestMonth);bump(salesSpvCounts,sales,spv)}if(spv&&gud)addAgg(getMap(spvGudMap,`${spv}\u0001${gud}`,{spv,gudang:gud}),r,latestYear,latestMonth);if(sales&&gud){const sg=`${sales}\u0001${gud}`;addAgg(getMap(salesGudMap,sg,{salesman:sales,gudang:gud}),r,latestYear,latestMonth);bump(salesGudSpvCounts,sg,spv)};
    const sisa=n(r['Sisa Piutang']),klas=String(r.klasifikasi||'').trim();if(sisa>0&&BUCKETS.includes(klas)){const noFaktur=String(r['No. Faktur']||'').trim(),noSJ=String(r['No SJ']||'').trim(),idCustomer=String(r['ID Customer']||'').trim();openInvoices.push({rowId:[noFaktur,noSJ,idCustomer,sales,spv,gud].join('|'),tanggalFaktur:excelDate(r['Tanggal Faktur']),overdueHari:n(r['overdue hari']),klasifikasi:klas,noSJ,noFaktur,idCustomer,customer:String(r.Customer||'').trim(),salesman:sales,spv,gudang:gud,totalPembelian:n(r['Total pembelian']),cash:n(r.Cash),sudahBayar:n(r['Sudah Bayar']),sisaPiutang:sisa,historiSales:String(r['Histori Sales']||'').trim(),historiKesimpulan:String(r['Histori Kesimpulan']||'').trim(),historiTerupdate:String(r['Histori Terupdate']||'').trim()})}}
  const salesRows=[...salesMap].map(([key,a])=>({...a,spv:dominant(salesSpvCounts.get(key))}));const salesGudRows=[...salesGudMap].map(([key,a])=>({...a,spv:dominant(salesGudSpvCounts.get(key))}));return{version:2,sourceFile:file.name,period:{year:latestYear,month:latestMonth,label:`${monthNames[latestMonth-1]} ${latestYear}`},company,spvs:[...spvMap].map(([spv,a])=>({spv,...a})),gudangs:[...gudMap].map(([gudang,a])=>({gudang,...a})),sales:salesRows,spvGudangs:[...spvGudMap.values()],salesGudangs:salesGudRows,openInvoices};
}
$('#processUploadBtn').addEventListener('click',async()=>{const file=$('#excelFile').files[0];if(!file)return toast('Pilih file Excel terlebih dahulu.','error');const btn=$('#processUploadBtn');btn.disabled=true;$('#uploadStatus').textContent=`Membaca ${file.name} (${(file.size/1024/1024).toFixed(1)} MB)...`;try{const payload=await parseExcel(file);$('#uploadStatus').textContent=`Periode: ${payload.period.label}\nSPV: ${payload.spvs.length}\nGudang: ${payload.gudangs.length}\nSales entity: ${payload.sales.length}\nOutstanding invoice: ${payload.openInvoices.length.toLocaleString('id-ID')}\nMenyimpan ke server...`;const result=await api('/data',{method:'POST',body:JSON.stringify(payload)});$('#uploadStatus').textContent=`BERHASIL\nData aktif: ${result.meta.period.label}\nSumber: ${result.meta.sourceFile}\nUpdate: ${dateText(result.meta.uploadedAt)}`;toast('Data Excel terbaru berhasil diaktifkan.');$('#spvFilter').value='';$('#salesFilter').value='';$('#gudangFilter').value='';await loadData()}catch(e){$('#uploadStatus').textContent=`GAGAL: ${e.message}`;toast(e.message,'error')}finally{btn.disabled=false}})

$('#downloadBtn').addEventListener('click',()=>{if(!window.XLSX)return toast('Library Excel belum siap.','error');const d=state.data,wb=XLSX.utils.book_new();const sum=[['KPI','Aktual','Target','Bobot','Weighted Score','Status'],...d.summary.kpi.details.map(x=>[x.label,x.actual,x.target,x.weight,x.weightedScore,x.status]),['TOTAL ADJUSTED SCORE','','','',''+d.summary.kpi.totalScore,d.summary.kpi.status],['Exposure Level',d.summary.kpi.exposure.level,'Weight',d.summary.kpi.exposure.weight]];XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet(sum),'Ringkasan KPI');
  const salesRank=d.rankings.sales.map(x=>({Rank:x.rank,SPV:x.spv,Gudang:x.gudang||'',Salesman:x.salesman,'Penjualan':x.salesPeriod,'Piutang':x.piutang,'Adjusted Score':x.kpi.totalScore,Status:x.kpi.status,Exposure:x.kpi.exposure.level,'Exposure Weight':x.kpi.exposure.weight,'Raw >30':x.kpi.over30Raw,'Adjusted >30':x.kpi.over30Adjusted,'Raw >120':x.kpi.over120Raw,'Adjusted >120':x.kpi.over120Adjusted,'C1/Sales':x.kpi.c1SalesRatio}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(salesRank),'Ranking Sales');
  const spvRank=d.rankings.spv.map(x=>({Rank:x.rank,SPV:x.spv,Gudang:x.gudang||'','Penjualan':x.salesPeriod,'Piutang':x.piutang,'Adjusted Score':x.kpi.totalScore,Status:x.kpi.status}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(spvRank),'Ranking SPV');
  const ir=filteredInvoices().map(x=>({Aging:x.klasifikasi,Faktur:x.noFaktur,'Tanggal Faktur':x.tanggalFaktur,Customer:x.customer,Gudang:x.gudang,SPV:x.spv,Salesman:x.salesman,'Sisa Piutang':x.sisaPiutang,'Overdue Hari':x.overdueHari,'Histori Sales':x.historiSales,'Histori Kesimpulan':x.historiKesimpulan,'Histori Terupdate':x.historiTerupdate,'Update Manual':x.manualHistory?.text||'','Update Oleh':x.manualHistory?.updatedBy||'','Update Waktu':x.manualHistory?.updatedAt||''}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(ir),'Aging Histori');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d.kpiParameters),'Parameter KPI');const sc=d.meta.scope,scope=[sc.gudang,sc.spv,sc.salesman].filter(Boolean).join('_')||'Perusahaan';XLSX.writeFile(wb,`Performance_Piutang_${scope.replace(/[^A-Za-z0-9_-]+/g,'_')}_${d.meta.period.label.replace(' ','_')}.xlsx`)})

function renderUserFormOptions(){const lookup=state.adminLookup||state.data;if(!lookup)return;$('#newSpv').innerHTML=optionsHtml(lookup.options.spvs,'Pilih SPV');updateSalesUserOptions();$('#newRole').dispatchEvent(new Event('change'))}
function updateSalesUserOptions(){const spv=$('#newSpv').value,all=(state.adminLookup||state.data)?.salesPerformance||[],names=[...new Set(all.filter(x=>!spv||x.spv===spv).map(x=>x.salesman))].sort();$('#newSalesman').innerHTML=optionsHtml(names,'Pilih Salesman')}
$('#newSpv').addEventListener('change',updateSalesUserOptions);$('#newRole').addEventListener('change',()=>{const role=$('#newRole').value;$('#userSpvWrap').classList.toggle('hidden',role==='company');$('#userSalesWrap').classList.toggle('hidden',role!=='sales')});
async function loadUsers(){try{const[u,d]=await Promise.all([api('/users'),api('/data')]);state.users=u.users;state.adminLookup=d;renderUsers();renderUserFormOptions()}catch(e){toast(e.message,'error')}}
function renderUsers(){$('#userTable').innerHTML=state.users.map(u=>`<tr><td><strong>${esc(u.username)}</strong></td><td>${esc(u.displayName)}</td><td>${esc(u.role)}</td><td>${esc(u.role==='sales'?`${u.spv} / ${u.salesman}`:u.spv||'Semua')}</td><td><button class="btn btn-ghost delete-user" data-user="${esc(u.username)}">Hapus</button></td></tr>`).join('')||'<tr><td colspan="5">Belum ada user tambahan.</td></tr>';$$('.delete-user').forEach(b=>b.addEventListener('click',async()=>{if(!confirm(`Hapus user ${b.dataset.user}?`))return;try{const d=await api(`/users?username=${encodeURIComponent(b.dataset.user)}`,{method:'DELETE'});state.users=d.users;renderUsers();toast('User dihapus.')}catch(e){toast(e.message,'error')}}))}
$('#userForm').addEventListener('submit',async e=>{e.preventDefault();const role=$('#newRole').value,body={displayName:$('#newDisplayName').value,username:$('#newUsername').value,password:$('#newPassword').value,role,spv:role==='company'?'':$('#newSpv').value,salesman:role==='sales'?$('#newSalesman').value:''};try{const d=await api('/users',{method:'POST',body:JSON.stringify(body)});state.users=d.users;renderUsers();e.target.reset();$('#newRole').dispatchEvent(new Event('change'));toast('User berhasil dibuat.')}catch(err){toast(err.message,'error')}})
boot();
